### login success

POST http://localhost:9080/login
Content-Type: application/json

{"username":"admin","password":"admin"}

> {%
client.test("Request executed successfully", function (){
    client.assert(response.status === 200, "Response status is not 200");
    var jwt = response.body
    client.global.set("jwt", response.body)
});
%}


###
GET http://localhost:9080/api/manufacturers
Authorization: Bearer {{jwt}}